### ISSUE TITLE
Ruler configuration

### ISSUE THREAD

**Issue by Fnige** [liamoconnor87/thereadingruler#1]
Nice extension, would you be able to please add some settings?

Some that I can think of off the top of my head would be:
- Ruler position (Above, On or **Below** the cursor)
- Opacity 
- Colour
- Keybind (For toggling the ruler)
- Maybe more but im tired so idk

Thank you!

**Comment by liamoconnor87** [comment]
Hello! Thank you for the feedback. I had plans for some of these already.
The cursor positioning I hadn't thought of :)

Will implement these at some point, let me know if you have anymore
suggestions.

Thanks again :)
